info:
  contact: {}
paths:
  /api/hello:
    get:
      consumes:
      - application/json
      description: sayhello
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: SayHello
swagger: "2.0"
